### ISSUE TITLE
Handling a FORMAT that is inaccurate

### ISSUE THREAD

**Issue by carbocation** [brentp/vcfgo#11]
Interestingly, my genotypes are not parsing, but it turns out this is an issue with the FORMAT. The FORMAT indicates: `GT:AD:DP`, but only the data that is actually provided for each sample is the genotype (e.g., `0/0`). 

This feels like it is is against spec, which is why it's not parsing. If I manually fix one of these lines, the genotype parses correctly. Weirdly, though, vcf-validate (from vcftools) does not complain about this FORMAT/data mismatch. I would interpret the spec the same way you did, though I'm a bit perplexed that vcf-validate is OK with this. Just want to make sure this is the right approach (I think it is).

**Comment by carbocation** [comment]
This is pretty hacky, but my it looks like I can just wrap my `io.Reader` and do an exact match, then replace the offending string with the correct one. (I'm doing this since this affects a few terabytes of files that I can't rewrite.) There is probably something more efficient than what I'm doing here.

```go
type formatReader struct {
	r io.Reader
}

func (m *formatReader) Read(p []byte) (n int, err error) {
	n, err = m.r.Read(p)
	bufString := string(p)

	// If the string does not contain the offending phrase, there is nothing to
	// do.
	if !strings.Contains(bufString, "GT:AD:DP:GQ:PL") {
		return
	}

	buf := []byte(strings.Replace(bufString, "GT:AD:DP:GQ:PL", "GT", -1))

	for i := range p {
		if i < len(buf) {
			// Overwrite the outer buffer
			p[i] = buf[i]
		} else {
			// But if we have reached the end of the inner buffer, zero out
			// the rest of the outer buffer
			p[i] = 0
		}
	}

	return
}
```

**Comment by brentp** [comment]
does `bcftoos view $vcf > /dev/null` on your vcf complain? 

unless I'm misunderstanding, you'd better use bufio.ReadString('\n') otherwise you could get part of the format field.

**Comment by carbocation** [comment]
Thanks for your help. On a subsetted file, it doesn't seem to complain, except about the contig not being listed:
```
$ bcftools view test.test > /dev/null
[W::vcf_parse] Contig '22' is not defined in the header. (Quick workaround: index the file with tabix.)
```

I'm running it on the full chromosome 22 now and no new errors yet, but will post an update if it does register an error.

I might be misunderstanding your ReadString comment, but my goal here is to replace the format field. I'll need to test this more to confirm that it doesn't introduce issues, but in my limited testing, this is doing what I expected.

**Comment by carbocation** [comment]
Just to close things out / clarify:

1. I reopened the issue when `bcftools` didn't spit out an error, because it seems that other bioinformatics tools are OK with this FORMAT field despite it being incorrect. So, I think it makes sense to decide one way or another. Your current approach feels the most correct to me, but I just want to make sure that's how you want it to be even if it differs in behavior from `bcftools` in this regard. If you wanted it to be permissive, you could read left -> right and just leave unpopulated fields (that the FORMAT asserts should exist, but don't) empty. But, I think that feels less correct than what you are currently doing.
1. I still have not run into any issues from my io.Reader wrapper. To clarify how I'm using it:

```go
vcf := "/path/to.vcf"
f, _ := os.Open(vcf)
fWrap := &formatReader{f}
rdr, _ := vcfgo.NewReader(fWrap, false)
...
```

**Comment by carbocation** [comment]
So you were definitely right - this hack seems to corrupt the output. However, I wasn't noticing it because by chance, the last sample was never corrupted. I noticed some count inconsistencies, which eventually led me to discover that invalid lazy sample parsing was not being reported (pull request is #12 ).

Here is a second approach for fixing the invalid format uses your `bufio.ReadString("\n")` suggestion. Look any better? Seems to not have the problems that the first approach did...

```go
type formatReader struct {
	r        *bufio.Reader
	leftover *strings.Reader
}

func NewFormatReader(r io.Reader) *formatReader {
	return &formatReader{r: bufio.NewReader(r), leftover: &strings.Reader{}}
}

func (m *formatReader) Read(p []byte) (n int, err error) {
	if m.leftover.Len() == 0 {
		line, err := m.r.ReadString('\n')
		line = strings.Replace(line, "GT:AD:DP:GQ:PL", "GT", -1)
		if err != nil {
			return len(line), err
		}
		m.leftover = strings.NewReader(line)
	}

	n, err = m.leftover.Read(p)

	return
}
```

**Comment by carbocation** [comment]
The latest workaround seems to run without error, so I'm closing this since this is something that should not be supported generally.
