### ISSUE TITLE
INFO with `Number=.,Type=String` parsed as `string` or `[]string`.

### ISSUE THREAD

**Issue by liserjrqlxue** [brentp/vcfgo#18]
I parse `INFO.CSQ` with header line `##INFO=<ID=CSQ,Number=.,Type=String,Description="`.
I found that `variant.Info_.Get("CSQ")` will return `interface{}` as `string` or `[]string`.
I use `switch` to handle this uncertain.
```
switch csqInfos.(type){
case string:
  // handle as string
case []string:
  // handle as []string
}
```
I wonder if there are more efficient and simpler way.

**Comment by brentp** [comment]
Yes, that's probably the best way. Is there a reason you're using `Info_` instead of [Info](https://pkg.go.dev/github.com/brentp/vcfgo#Variant.Info) ?

**Comment by liserjrqlxue** [comment]
I found `v.Info()` is a function simply return `v.Info_`.
Since `Info` is public, I use it directly.
Emmm, is using `struct method` more general and more stable?

**Comment by brentp** [comment]
Yes, it's fine to use `v.INFO_`. I haven't done any development on vcfgo for a while so I had forgotten.
