### ISSUE TITLE
Issue getting genotype info

### ISSUE THREAD

**Issue by matthdsm** [brentp/vcfgo#19]
Hi,

I'm trying to use vcfgo in a rewrite of a tool I'm working on. I was following the example in the readme, but I can't seem to get it to work.

No matter what vcf I load, always get an empty `samples` slice when querying the samples from the `variant` variable.

Example of the function:
https://go.dev/play/p/ne1C6QmMjWQ

Any idea what I'm doing wrong?

Thanks
Matthias

**Comment by brentp** [comment]
Hi Matthias,
`vcfgo` has a `lazySamples` aregument to the `NewReader` function: https://github.com/brentp/vcfgo/blob/b340b4d67893390de09ab9c64d3ab55c02d37143/reader.go#L59

I think you can also call ParseSamples directly since it's public (from the header): https://github.com/brentp/vcfgo/blob/b340b4d67893390de09ab9c64d3ab55c02d37143/reader.go#L224-L227

hope this helps,
-Brent

**Comment by matthdsm** [comment]
Hi Brent,

 Thanks for the info, but I don't use the `NewReader` function directly, but through the `irelate/parsers` package.
My main issue is that the genotype interface seems to be empty.

Example code to get the genotype depth:
```	
for i := range variant.Header.SampleNames {
		DP, err := variant.GetGenotypeField(variant.Samples[i], "DP", 0)
		if err != nil {
			log.Println("Variant does not have a DP field: ", variant)
		}
		fmt.Println(DP)
	}
```

This just returns nothing.

**Comment by matthdsm** [comment]
```
	err := variant.Header.ParseSamples(variant)
	if err != nil {
		log.Println("Error parsing samples: ", err)
	}
	fmt.Println(variant.Samples[0])
	//empty return
```

**Comment by brentp** [comment]
can you post a link or the code for your current function?

**Comment by matthdsm** [comment]
Sure! Here's the whole thing!
https://github.com/matthdsm/Hopla-go/blob/rewrite/go/hopla.go#L84

**Comment by brentp** [comment]
I would add some debug statements into https://github.com/brentp/vcfgo/blob/master/header.go#L69
to see what's happening (and make sure that's called).

**Comment by matthdsm** [comment]
Found the issue! Turns out the `variant` variable was `nil` ... As expected, it was my fault.

Thanks for the help!
