### ISSUE TITLE
Genotype parsing does not handle Haploid/Triploid

### ISSUE THREAD

**Issue by tylerwmarrs** [brentp/vcfgo#3]
Per the VCF specification. Genotype field for a sample can be diploid, haploid or triploid. It appears you are mainly concerned with diploid calls in your unit tests, however there is an issue in parsing haploid genotypes. Right now there is an index out of range error being thrown.

The X, Y and MT chromosomes may contain only haploid calls. Is there any way that you can adjust your logic? If you are unable to fix this, I can try to find some time to do so.

**Comment by tylerwmarrs** [comment]
I found a pretty easy fix to the issue. This line is causing the problem:
https://github.com/brentp/vcfgo/blob/master/header.go#L156

Changing the line to this fixes the issue:
else if len(value) == 3 && (value[1] == '/' || value[1] == '|')

**Comment by brentp** [comment]
can you add your VCF so I can use it as a test-case? should be an easy fix but I don't have much non-diploid data.

**Comment by tylerwmarrs** [comment]
Here you go. I only have sample data with diploid, however your logic should work for triploid after you make the suggested correction.

[sample_haploid_snps.txt](https://github.com/brentp/vcfgo/files/224081/sample_haploid_snps.txt)

**Comment by tylerwmarrs** [comment]
Here you go. I only have sample data with haploid, however your logic should work for triploid after you make the suggested correction.

[sample_haploid_snps.txt](https://github.com/brentp/vcfgo/files/224089/sample_haploid_snps.txt)

**Comment by brentp** [comment]
cheers. I hope to get to this by next week.

**Comment by brentp** [comment]
closed by #7100e41199909b73c5be
