### ISSUE TITLE
Does not correctly parse multi allelic genotypes

### ISSUE THREAD

**Issue by akotlar** [brentp/vcfgo#5]
File: [ALL.chr22.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf (1000 genomes)](http://hgdownload.cse.ucsc.edu/gbdb/hg19/1000Genomes/phase3/ALL.chr22.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz)

Position: 16061250

Result: 0, 1 genotypes parse correctly, 2 is ignored.

(*vcfgo.SampleGenotype)(0x4206be420)({
  Phased: (bool) true,
  GT: ([]int) (cap=2) {
  },
  DP: (int) 0,
  GL: ([]float64) (cap=3) {
  },
  GQ: (int) 0,
  MQ: (int) 0,
  Fields: (map[string]string) (len=1) {
   (string) (len=2) "GT": (string) (len=3) "2|2"
  }
 })

**Comment by brentp** [comment]
I've just pushed a fix for this. The samples stuff (and the multi-allelic stuff) is less tested as I haven't used it much, but please continue to let me know any issues and I'll get them resolved. 
Thanks for reporting.

**Comment by akotlar** [comment]
This is the fastest response I've ever seen on an issue. Thank you. Starring this.
